env: standard
runtime: nodejs12

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(json|ico|js|pdf|jpg))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js|pdf|jpg)$

  - url: .*
    static_files: build/index.html
    upload: build/index.html
